version: '3.7'

services:
  democlean.webapi:    
    environment:
      DEMOCLEAN_CONN: Host=democlean.database;Port=5432;Database=DemoClean;User Id=postgres;Password=postgres;
    ports:
      - 8081:80      
    networks:
      - democleanarchitecture-network
    depends_on:
      - democlean.database

  democlean.database:
    image: postgres:9.5
    restart: always
    environment:  
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - democleanarchitecture-network

volumes:  
  pgdata:  

networks:
  democleanarchitecture-network: